
services:

# ---------------------------------------------------------------------------------------------------------

  gateway:
    build: 
      context: .
      dockerfile: dockerfile.gateway  
    container_name: web-gateway
    volumes:
      - ./web_proxy_nginx:/usr/share/nginx/html
      - ./web_proxy_nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "6688:8080"
    depends_on:
      - auth-service         

  auth-service:
    image: node:18-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./web_proxy_node:/app 
    command: sh -c "npm install express body-parser cors express-session mongoose && node server.js"
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"      

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./web_proxy_mongo:/data/db
    ports:
      - "27017:27017"

# -------------------------------------------------------------------------------------------------------
# Kali Linux Webtop Configuration (using Anchor to keep it clean)

  webtop1: &kali-config
    # build: 
    #   context: .
    #   dockerfile: dockerfile.webtop    
    image: lscr.io/linuxserver/webtop:ubuntu-xfce  
    # image: lscr.io/linuxserver/kali-linux:latest
    container_name: webtop1
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - SUBFOLDER=/webtop1/
    shm_size: "2gb" # เพิ่มเป็น 2gb เพื่อกัน Browser Crash
    restart: unless-stopped


    

  webtop2:
    <<: *kali-config
    container_name: webtop2
    environment:
      - SUBFOLDER=/webtop2/

  # webtop3:
  #   <<: *kali-config
  #   container_name: webtop3
  #   environment:
  #     - SUBFOLDER=/webtop3/

  # webtop4:
  #   <<: *kali-config
  #   container_name: webtop4
  #   environment:
  #     - SUBFOLDER=/webtop4/

  # webtop5:
  #   <<: *kali-config
  #   container_name: webtop5
  #   environment:
  #     - SUBFOLDER=/webtop5/

  # webtop6:
  #   <<: *kali-config
  #   container_name: webtop6
  #   environment:
  #     - SUBFOLDER=/webtop6/

  # webtop7:
  #   <<: *kali-config
  #   container_name: webtop7
  #   environment:
  #     - SUBFOLDER=/webtop7/

  # webtop8:
  #   <<: *kali-config
  #   container_name: webtop8
  #   environment:
  #     - SUBFOLDER=/webtop8/

  # webtop9:
  #   <<: *kali-config
  #   container_name: webtop9
  #   environment:
  #     - SUBFOLDER=/webtop9/

  # webtop10:
  #   <<: *kali-config
  #   container_name: webtop10
  #   environment:
  #     - SUBFOLDER=/webtop10/

  # webtop11:
  #   <<: *kali-config
  #   container_name: webtop11
  #   environment:
  #     - SUBFOLDER=/webtop11/

  # webtop12:
  #   <<: *kali-config
  #   container_name: webtop12
  #   environment:
  #     - SUBFOLDER=/webtop12/

  # webtop13:
  #   <<: *kali-config
  #   container_name: webtop13
  #   environment:
  #     - SUBFOLDER=/webtop13/

  # webtop14:
  #   <<: *kali-config
  #   container_name: webtop14
  #   environment:
  #     - SUBFOLDER=/webtop14/

  # webtop15:
  #   <<: *kali-config
  #   container_name: webtop15
  #   environment:
  #     - SUBFOLDER=/webtop15/

  # webtop16:
  #   <<: *kali-config
  #   container_name: webtop16
  #   environment:
  #     - SUBFOLDER=/webtop16/

  # webtop17:
  #   <<: *kali-config
  #   container_name: webtop17
  #   environment:
  #     - SUBFOLDER=/webtop17/

  # webtop18:
  #   <<: *kali-config
  #   container_name: webtop18
  #   environment:
  #     - SUBFOLDER=/webtop18/

  # webtop19:
  #   <<: *kali-config
  #   container_name: webtop19
  #   environment:
  #     - SUBFOLDER=/webtop19/

  # webtop20:
  #   <<: *kali-config
  #   container_name: webtop20
  #   environment:
  #     - SUBFOLDER=/webtop20/

  # webtop21:
  #   <<: *kali-config
  #   container_name: webtop21
  #   environment:
  #     - SUBFOLDER=/webtop21/

  # webtop22:
  #   <<: *kali-config
  #   container_name: webtop22
  #   environment:
  #     - SUBFOLDER=/webtop22/

  # webtop23:
  #   <<: *kali-config
  #   container_name: webtop23
  #   environment:
  #     - SUBFOLDER=/webtop23/

  # webtop24:
  #   <<: *kali-config
  #   container_name: webtop24
  #   environment:
  #     - SUBFOLDER=/webtop24/

  # webtop25:
  #   <<: *kali-config
  #   container_name: webtop25
  #   environment:
  #     - SUBFOLDER=/webtop25/

  # webtop26:
  #   <<: *kali-config
  #   container_name: webtop26
  #   environment:
  #     - SUBFOLDER=/webtop26/

  # webtop27:
  #   <<: *kali-config
  #   container_name: webtop27
  #   environment:
  #     - SUBFOLDER=/webtop27/

  # webtop28:
  #   <<: *kali-config
  #   container_name: webtop28
  #   environment:
  #     - SUBFOLDER=/webtop28/

  # webtop29:
  #   <<: *kali-config
  #   container_name: webtop29
  #   environment:
  #     - SUBFOLDER=/webtop29/

  # webtop30:
  #   <<: *kali-config
  #   container_name: webtop30
  #   environment:
  #     - SUBFOLDER=/webtop30/