worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # ใช้ DNS Docker (สำคัญมากสำหรับการอ้างอิงชื่อ Container)
    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 6688; # แนะนำให้ใช้ 80 ภายใน Container

        # โฟลเดอร์เก็บไฟล์ HTML (Map จาก ./web_porxy_nginx ใน docker-compose)
        root /usr/share/nginx/html;
        index index.html;

        # --------------------------------------------------------
        # 1. API Proxy (Backend Node.js)
        # --------------------------------------------------------
        location /api/ {
            # 🔥 ลบ rewrite ออก เพื่อให้ส่ง /api/login ไปหา Node.js ได้ถูกต้อง
            proxy_pass http://localhost:3100; 
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # --------------------------------------------------------
        # 2. หน้าเว็บหลัก (Login & Dashboard)
        # --------------------------------------------------------
        location / {
            # พยายามหาไฟล์ตามชื่อ -> ถ้าไม่เจอให้ไป index.html (สำหรับ SPA)
            try_files $uri $uri/ /index.html;
        }

        # หน้า Error
        error_page 404 500 502 503 504 /error.html;
        location = /error.html {
            internal;
        }
        # --------------------------------------------------------
        # . Webtop (Linux Desktop)
        # --------------------------------------------------------
# จับคู่: /webtop1 -> ส่งไป webtop1:3000/webtop1
        # จับคู่: /webtop2 -> ส่งไป webtop2:3000/webtop2
        
        location ~ ^/webtop(?<id>\d+)/ {
            resolver 127.0.0.11 valid=30s;
            
            # ไม่ต้องใส่ Path ต่อท้าย เพราะใน Docker เราแก้ SUBFOLDER ให้ตรงกันแล้ว
            # Nginx จะส่ง /webtop1/ ไปหา webtop1 ซึ่งรอรับที่ /webtop1/ อยู่แล้ว
            # proxy_pass https://webtop$id:3001;
            proxy_pass https://localhost:3001;
            # proxy_pass https://host.docker.internal:3001;


            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

 
        location ~ ^/proxy/(?<target_port>\d+)/(?<target_path>.*)$ {
            resolver 127.0.0.11;
            proxy_pass http://host.docker.internal:$target_port/$target_path$is_args$args;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_intercept_errors on;
        }
    }
}